In [1]:
import torch

### Tensor

In [10]:
x = torch.empty(2)
print(x)

x = torch.empty(2, 3)
print(x)

x = torch.zeros(2, 3)
print(x)

x = torch.rand(2, 3)
print(x)

x = torch.ones(2, 3)
print(x)
print(x.dtype)

x = torch.ones(2, 3, dtype=torch.int)
print(x.dtype)

x = torch.ones(2, 3)
print(x.size())

x = torch.tensor([2, 3])
print(x)
print(x.size())

tensor([1.1997e-10, 0.0000e+00])
tensor([[1.1325e-10, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.4423, 0.1775, 0.9793],
        [0.8245, 0.6558, 0.8836]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.float32
torch.int32
torch.Size([2, 3])
tensor([2, 3])
torch.Size([2])


In [11]:
y = x + 2
print(y)

x.requires_grad_(False)
print(x)

y = x.detach()
print(y)

y = x + 2
print(y)

with torch.no_grad():
    y = x + 2
    print(y)

tensor([4, 5])
tensor([2, 3])
tensor([2, 3])
tensor([4, 5])
tensor([4, 5])


In [4]:
x = torch.tensor(2.0, requires_grad=True)
y = x**2 + 3*x + 1
y.backward()

print(x)
print(x.grad)

tensor(2., requires_grad=True)
tensor(7.)


In [6]:
# Data
x = torch.tensor([1, 2, 3, 4, 5, 6], dtype=torch.float32)
# y = torch.tensor([2, 4, 6, 8, 10, 12], dtype=torch.float32)
y = torch.tensor([3, 5, 7, 9, 11, 13], dtype=torch.float32)

# init weight
w = torch.tensor(0.0, dtype=torch.float32, requires_grad=True)
print(w)

# model prediction
def forward(x):
    return w * x

# set up loss function as mean square error
def loss(y, y_predicted):
    return ((y_predicted-y) ** 2).mean()

# Training
learning_rate = 0.01
n_iters = 100

for epoch in range(n_iters):
    # perdiction = forward pass
    y_pred = forward(x)

    # loss
    l = loss(y, y_pred)

    # calculate dl/dw
    l.backward() 

    # update weights
    with torch.no_grad():
        w -= learning_rate * w.grad

    if epoch % 1 == 0:
        print(f'epoch {epoch + 1}: w = {w:.3f}, loss = {l:.8f}')
    
    # zero gradients，要記得歸零每次運算的 gradients，否則會累加
    w.grad.zero_()

print(f'Prediction after training: f(5) = {forward(5): .3f}')

tensor(0., requires_grad=True)
epoch 1: w = 0.677, loss = 75.66666412
epoch 2: w = 1.148, loss = 36.82336807
epoch 3: w = 1.476, loss = 17.97099113
epoch 4: w = 1.705, loss = 8.82109165
epoch 5: w = 1.865, loss = 4.38023996
epoch 6: w = 1.976, loss = 2.22489786
epoch 7: w = 2.053, loss = 1.17881405
epoch 8: w = 2.107, loss = 0.67110348
epoch 9: w = 2.145, loss = 0.42468837
epoch 10: w = 2.171, loss = 0.30509272
epoch 11: w = 2.189, loss = 0.24704708
epoch 12: w = 2.202, loss = 0.21887507
epoch 13: w = 2.210, loss = 0.20520197
epoch 14: w = 2.217, loss = 0.19856580
epoch 15: w = 2.221, loss = 0.19534503
epoch 16: w = 2.224, loss = 0.19378185
epoch 17: w = 2.226, loss = 0.19302319
epoch 18: w = 2.227, loss = 0.19265491
epoch 19: w = 2.228, loss = 0.19247620
epoch 20: w = 2.229, loss = 0.19238949
epoch 21: w = 2.230, loss = 0.19234735
epoch 22: w = 2.230, loss = 0.19232696
epoch 23: w = 2.230, loss = 0.19231701
epoch 24: w = 2.230, loss = 0.19231229
epoch 25: w = 2.231, loss = 0.19230990


In [7]:
# Data
x = torch.tensor([1, 2, 3, 4, 5, 6], dtype=torch.float32)
# y = torch.tensor([2, 4, 6, 8, 10, 12], dtype=torch.float32)
y = torch.tensor([3, 5, 7, 9, 11, 13], dtype=torch.float32)

# init weight
w = torch.tensor(0.0, dtype=torch.float32, requires_grad=True)
b = torch.tensor(0.0, dtype=torch.float32, requires_grad=True)
print(w, b)

# model prediction
def forward(x):
    return w * x + b

# set up loss function as mean square error
def loss(y, y_predicted):
    return ((y_predicted-y) ** 2).mean()

# Training
learning_rate = 0.01
n_iters = 100

for epoch in range(n_iters):
    # perdiction = forward pass
    y_pred = forward(x)

    # loss
    l = loss(y, y_pred)

    # calculate dl/dw
    l.backward() 

    # update weights
    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad

    if epoch % 1 == 0:
        print(f'epoch {epoch + 1}: w = {w:.3f}, b = {b:.3f}, loss = {l:.8f}')
    
    # zero gradients，要記得歸零每次運算的 gradients，否則會累加
    w.grad.zero_()
    b.grad.zero_()

print(f'Prediction after training: f(5) = {forward(5): .3f}')

tensor(0., requires_grad=True) tensor(0., requires_grad=True)
epoch 1: w = 0.677, b = 0.160, loss = 75.66666412
epoch 2: w = 1.137, b = 0.269, loss = 35.04683304
epoch 3: w = 1.450, b = 0.344, loss = 16.24656868
epoch 4: w = 1.663, b = 0.396, loss = 7.54505348
epoch 5: w = 1.807, b = 0.432, loss = 3.51754498
epoch 6: w = 1.905, b = 0.457, loss = 1.65330660
epoch 7: w = 1.972, b = 0.474, loss = 0.79029655
epoch 8: w = 2.017, b = 0.487, loss = 0.39068758
epoch 9: w = 2.048, b = 0.496, loss = 0.20555431
epoch 10: w = 2.069, b = 0.502, loss = 0.11968931
epoch 11: w = 2.083, b = 0.507, loss = 0.07976940
epoch 12: w = 2.092, b = 0.512, loss = 0.06111584
epoch 13: w = 2.098, b = 0.515, loss = 0.05230607
epoch 14: w = 2.102, b = 0.518, loss = 0.04805367
epoch 15: w = 2.105, b = 0.520, loss = 0.04591171
epoch 16: w = 2.107, b = 0.522, loss = 0.04474789
epoch 17: w = 2.108, b = 0.524, loss = 0.04403807
epoch 18: w = 2.108, b = 0.526, loss = 0.04353959
epoch 19: w = 2.109, b = 0.528, loss = 0.043